version: "3.3"

services:

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./sql_config:/config
    ports:
      - "8200:3000"
      - "8201:3001"
    restart: unless-stopped







    